/* ============================================================
   Raedworkouts — data.js
   Single source of truth for the exercise library and programme.
   Edit this file (or use the in-app Library editor) to add
   alternatives, change videos, or update the programme.
   ============================================================ */

// ---- Helpers -------------------------------------------------
const yt = (id) => `https://www.youtube.com/watch?v=${id}`;
const ytShort = (id) => `https://www.youtube.com/shorts/${id}`;
const thumb = (id) => `https://img.youtube.com/vi/${id}/hqdefault.jpg`;

// Body illustration per primary muscle. Returns a relative path
// to a colored anatomy image in /img/. Falls back to a default.
const BODY_IMG = {
  chest: './img/body_chest.png',
  upper_chest: './img/body_chest.png',
  shoulders: './img/body_chest.png',     // upper-body card uses chest body until shoulders illustration is added
  side_delts: './img/body_chest.png',
  rear_delts: './img/body_back.png',
  triceps: './img/body_bicep.png',       // arm illustration covers triceps too (single-arm view)
  biceps: './img/body_bicep.png',
  forearms: './img/body_bicep.png',
  back: './img/body_back.png',
  upper_back: './img/body_back.png',
  abs: './img/body_chest.png',
  quads: './img/body_quads.png',
  hamstrings: './img/body_glutes.png',
  glutes: './img/body_glutes.png',
  calves: './img/body_calves.png',
};
const bodyImg = (primary_arr) => {
  const m = (primary_arr && primary_arr[0]) || 'chest';
  return BODY_IMG[m] || './img/body_chest.png';
};

// ---- Muscle groups ------------------------------------------
const MUSCLES = {
  chest: { en: 'Chest', ar: 'صدر', region: 'anterior' },
  upper_chest: { en: 'Upper Chest', ar: 'الصدر العلوي', region: 'anterior' },
  shoulders: { en: 'Shoulders', ar: 'أكتاف', region: 'anterior' },
  side_delts: { en: 'Side Delts', ar: 'الكتف الجانبي', region: 'anterior' },
  triceps: { en: 'Triceps', ar: 'تراي', region: 'anterior' },
  quads: { en: 'Quads', ar: 'مقدمة الفخذ', region: 'anterior' },
  abs: { en: 'Abs', ar: 'بطن', region: 'anterior' },
  back: { en: 'Back / Lats', ar: 'ظهر', region: 'posterior' },
  upper_back: { en: 'Upper Back', ar: 'ظهر علوي', region: 'posterior' },
  rear_delts: { en: 'Rear Delts', ar: 'الكتف الخلفي', region: 'posterior' },
  biceps: { en: 'Biceps', ar: 'باي', region: 'posterior' },
  forearms: { en: 'Forearms', ar: 'ساعد', region: 'posterior' },
  glutes: { en: 'Glutes', ar: 'أرداف', region: 'posterior' },
  hamstrings: { en: 'Hamstrings', ar: 'خلف الفخذ', region: 'posterior' },
  calves: { en: 'Calves', ar: 'سمانة', region: 'posterior' },
};

// ---- Exercise library ---------------------------------------
// Each exercise: id, name, muscles, mohannad_videos[], jeff_nippard, alternatives[], notes
const EXERCISES = [
  // ====== UPPER BODY — PUSH ======
  {
    id: 'incline_chest_press',
    name: 'Incline Chest Press (Machine)',
    name_ar: 'بنش مايل (آلة)',
    primary: ['upper_chest'],
    secondary: ['shoulders', 'triceps'],
    pattern: 'horizontal_push',
    mohannad: ['-PT6BQcrm_I', 'wMksQXD01K0', 'o0Ud3RU59hw'],
    jeff_nippard: 'https://www.youtube.com/shorts/xGMqmmn5Z7Q',
    alternatives: ['chest_press_machine', 'incline_db_press'],
    cue: 'Set bench 30°. Drive elbows down and in, no flare.',
  },
  {
    id: 'chest_press_machine',
    name: 'Chest Press Machine',
    name_ar: 'بنش آلة',
    primary: ['chest'],
    secondary: ['shoulders', 'triceps'],
    pattern: 'horizontal_push',
    mohannad: ['Q1S9ybWYMjE', 'ogj1igwlc9I'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=chest+press+machine+jeff+nippard',
    alternatives: ['incline_chest_press', 'pec_dec'],
    cue: 'Handles in line with mid-chest. Squeeze pecs at lockout.',
  },
  {
    id: 'chest_fly',
    name: 'Chest Fly Machine',
    name_ar: 'تفتيح صدر آلة',
    primary: ['chest'],
    secondary: ['shoulders'],
    pattern: 'isolation_push',
    mohannad: ['g3T7LsEeDWQ', 'iEvy-65Q5g4', 'fgXSA2-o0NM'],
    jeff_nippard: 'https://www.youtube.com/watch?v=-EIhKMDSjBY',
    alternatives: ['pec_dec', 'cable_fly'],
    cue: 'Slight bend in elbows, lock them. Stretch deep, squeeze hard.',
  },
  {
    id: 'pec_dec',
    name: 'Pec Deck',
    name_ar: 'بكدك',
    primary: ['chest'],
    secondary: [],
    pattern: 'isolation_push',
    mohannad: ['GAPCETzYmuI'],
    jeff_nippard: 'https://www.youtube.com/watch?v=-EIhKMDSjBY',
    alternatives: ['chest_fly', 'cable_fly'],
    cue: 'Arms pinned to pads. Drive elbows together, not hands.',
  },
  {
    id: 'incline_db_press',
    name: 'Incline Dumbbell Press',
    name_ar: 'بنش مايل دمبل',
    primary: ['upper_chest'],
    secondary: ['shoulders', 'triceps'],
    pattern: 'horizontal_push',
    mohannad: [],
    jeff_nippard: 'https://www.youtube.com/shorts/xGMqmmn5Z7Q',
    alternatives: ['incline_chest_press', 'chest_press_machine'],
    cue: 'Bench at 30°. Press up and slightly in. Don\'t bang the bells at the top.',
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly (Crossover)',
    name_ar: 'تفتيح كيبل',
    primary: ['chest'],
    secondary: ['shoulders'],
    pattern: 'isolation_push',
    mohannad: [],
    jeff_nippard: 'https://www.youtube.com/watch?v=-EIhKMDSjBY',
    alternatives: ['chest_fly', 'pec_dec'],
    cue: 'Slight forward lean. Drive across the chest, brief squeeze, slow eccentric.',
  },
  {
    id: 'shoulder_press_machine',
    name: 'Shoulder Press (Machine/DB)',
    name_ar: 'ضغط أكتاف',
    primary: ['shoulders'],
    secondary: ['triceps', 'upper_chest'],
    pattern: 'vertical_push',
    mohannad: ['QjAoqZ6EpFg', 'WvLMauqrnK8'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=shoulder+press+jeff+nippard',
    alternatives: [],
    cue: 'Slight forward lean. Press up and slightly back, not behind your head.',
  },
  {
    id: 'lateral_raise_db',
    name: 'Lateral Raise (DB)',
    name_ar: 'رفعة جانبية دمبل',
    primary: ['side_delts'],
    secondary: [],
    pattern: 'isolation_push',
    mohannad: ['AyaiYr0RIwE', 'bB_FNepte6A'],
    jeff_nippard: 'https://www.youtube.com/shorts/jy8L7l-3hRI',
    alternatives: ['lateral_raise_cable'],
    cue: 'Lean slightly forward. Lead with elbows, pinky up at top.',
  },
  {
    id: 'lateral_raise_cable',
    name: 'Lateral Raise (Cable)',
    name_ar: 'رفعة جانبية كيبل',
    primary: ['side_delts'],
    secondary: [],
    pattern: 'isolation_push',
    mohannad: ['1AmmsXlf8MU'],
    jeff_nippard: 'https://www.youtube.com/shorts/HeovYNoZDRg',
    alternatives: ['lateral_raise_db'],
    cue: 'Cable from low pulley behind you. Constant tension wins.',
  },
  {
    id: 'seated_dips',
    name: 'Seated Dip Machine',
    name_ar: 'ديبس جالس',
    primary: ['triceps'],
    secondary: ['chest', 'shoulders'],
    pattern: 'compound_push',
    mohannad: ['KHPrFieVd6g', '2NOglxsG1wE'],
    jeff_nippard: 'https://www.youtube.com/watch?v=yN6Q1UI_xkE',
    alternatives: ['tricep_pushdown'],
    cue: 'Elbows tight to ribs. Full lockout at the bottom.',
  },
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown (Cable)',
    name_ar: 'ضغط ترايسبس كيبل',
    primary: ['triceps'],
    secondary: [],
    pattern: 'isolation_push',
    mohannad: [],
    jeff_nippard: 'https://www.youtube.com/watch?v=popGXI-qs98',
    alternatives: ['overhead_rope'],
    cue: 'Elbows pinned. Lockout with knuckles flexed away.',
  },
  {
    id: 'overhead_rope',
    name: 'Overhead Rope Tricep Extension',
    name_ar: 'تمديد ترايسبس فوق الرأس',
    primary: ['triceps'],
    secondary: [],
    pattern: 'isolation_push',
    mohannad: ['Q3bO1Fh4734', 'MiiLWxoz8fU'],
    jeff_nippard: 'https://www.youtube.com/watch?v=popGXI-qs98',
    alternatives: ['tricep_pushdown'],
    cue: 'Long head emphasis. Stretch deep at the bottom.',
  },

  // ====== UPPER BODY — PULL ======
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    name_ar: 'سحب علوي',
    primary: ['back'],
    secondary: ['biceps', 'rear_delts'],
    pattern: 'vertical_pull',
    mohannad: ['goIzUxshgGI', 'uqPK1Vz6Xks'],
    jeff_nippard: 'https://www.youtube.com/shorts/SqQxuEpXnF4',
    alternatives: ['lat_pulldown_neutral'],
    cue: 'Pull the bar to upper chest. Drive elbows down and back, not just bend them.',
  },
  {
    id: 'lat_pulldown_neutral',
    name: 'Lat Pulldown (Neutral Grip)',
    name_ar: 'سحب علوي قبضة محايدة',
    primary: ['back'],
    secondary: ['biceps'],
    pattern: 'vertical_pull',
    mohannad: ['goIzUxshgGI'],
    jeff_nippard: 'https://www.youtube.com/shorts/SqQxuEpXnF4',
    alternatives: ['lat_pulldown'],
    cue: 'Palms face each other. Better stretch on the lats, kinder on shoulders.',
  },
  {
    id: 'tbar_row',
    name: 'T-Bar Row',
    name_ar: 'سحب تي بار',
    primary: ['back'],
    secondary: ['rear_delts', 'biceps'],
    pattern: 'horizontal_pull',
    mohannad: ['36sT4np_G1E', '8bHhLWBAvBU'],
    jeff_nippard: 'https://www.youtube.com/shorts/fgSyNdEsqlM',
    alternatives: ['low_row_machine', 'seated_cable_row'],
    cue: 'Hinge to ~30°. Pull to lower ribs. Squeeze shoulder blades.',
  },
  {
    id: 'low_row_machine',
    name: 'Low Row Machine',
    name_ar: 'سحب آلة منخفض',
    primary: ['upper_back'],
    secondary: ['rear_delts', 'biceps'],
    pattern: 'horizontal_pull',
    mohannad: ['uLb1R5sjUw0', '2dbhfV8ErjY', 'yFo-EFYzf1s'],
    jeff_nippard: 'https://www.youtube.com/shorts/fgSyNdEsqlM',
    alternatives: ['tbar_row', 'seated_cable_row'],
    cue: 'Chest against the pad. Pull to ribs, no torso swing.',
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    name_ar: 'سحب كيبل جالس',
    primary: ['back'],
    secondary: ['biceps', 'rear_delts'],
    pattern: 'horizontal_pull',
    mohannad: ['z7C7PxVDAD0', 'dCLRdVqKRkk', 'fPbfYDgzIgA'],
    jeff_nippard: 'https://www.youtube.com/shorts/fgSyNdEsqlM',
    alternatives: ['low_row_machine', 'tbar_row'],
    cue: 'Stretch all the way forward. Pull to belly, brief squeeze.',
  },
  {
    id: 'face_pull',
    name: 'Face Pull (Cable)',
    name_ar: 'سحب الوجه',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    pattern: 'isolation_pull',
    mohannad: ['McDrW7uI4JI', 'DVxfKB0BnlY', 'TxoDSfcObdU'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=face+pull+jeff+nippard',
    alternatives: ['rear_delt_fly'],
    cue: 'Pull rope to forehead. External rotation at the top — keep elbows high.',
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly Machine',
    name_ar: 'تفتيح خلفي',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    pattern: 'isolation_pull',
    mohannad: ['dwb-ccqK1WE', 'PZq3CJGLj6M'],
    jeff_nippard: 'https://www.youtube.com/shorts/P5CXx_jgTDE',
    alternatives: ['face_pull'],
    cue: 'Lead with elbows, hands stay neutral. Slow eccentric.',
  },
  {
    id: 'biceps_curl',
    name: 'Biceps Curl (DB or Cable)',
    name_ar: 'باي سبس',
    primary: ['biceps'],
    secondary: ['forearms'],
    pattern: 'isolation_pull',
    mohannad: ['iui51E31sX8', 'cHxRJdSVIkA'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=bicep+curl+jeff+nippard',
    alternatives: ['hammer_curl'],
    cue: 'Elbows tucked. Don\'t swing — if you swing, the weight is too heavy.',
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    name_ar: 'هامر',
    primary: ['biceps'],
    secondary: ['forearms'],
    pattern: 'isolation_pull',
    mohannad: ['n87rX0fNkBQ', '8nCxfkRSN4o'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=hammer+curl+jeff+nippard',
    alternatives: ['biceps_curl', 'reverse_curl'],
    cue: 'Neutral grip. Targets brachialis — adds arm thickness.',
  },
  {
    id: 'reverse_curl',
    name: 'Reverse Curl',
    name_ar: 'باي عكسي',
    primary: ['forearms'],
    secondary: ['biceps'],
    pattern: 'isolation_pull',
    mohannad: ['jtOP4m8MXh4', '4U2tiGjXobY'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=reverse+curl+jeff+nippard',
    alternatives: ['hammer_curl'],
    cue: 'Overhand grip. Forearms will scream — that\'s the point.',
  },

  // ====== LOWER BODY ======
  {
    id: 'leg_press',
    name: 'Leg Press',
    name_ar: 'مكبس الرجل',
    primary: ['quads'],
    secondary: ['glutes', 'hamstrings'],
    pattern: 'compound_quad',
    mohannad: ['ahaJTts1f3s', 'vNaDK5l39_A'],
    jeff_nippard: 'https://www.youtube.com/shorts/nDh_BlnLCGc',
    alternatives: ['hack_squat'],
    cue: 'Feet shoulder-width, mid-platform. Don\'t let lower back round.',
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    name_ar: 'هاك سكوات',
    primary: ['quads'],
    secondary: ['glutes'],
    pattern: 'compound_quad',
    mohannad: ['tb5KeF00yII', 'udzewuz-BQY'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=hack+squat+jeff+nippard',
    alternatives: ['leg_press'],
    cue: 'Feet slightly forward of hips. Drive through whole foot.',
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    name_ar: 'تمديد الرجل',
    primary: ['quads'],
    secondary: [],
    pattern: 'isolation_quad',
    mohannad: ['1BIIORHJ2XI', 'XQeytI_bCsk'],
    jeff_nippard: 'https://www.youtube.com/shorts/ztNBgrGy6FQ',
    alternatives: [],
    cue: 'Pin to top, slow eccentric, don\'t bang the pin.',
  },
  {
    id: 'prone_leg_curl',
    name: 'Prone Leg Curl',
    name_ar: 'ثني الرجل بطن',
    primary: ['hamstrings'],
    secondary: ['glutes'],
    pattern: 'isolation_hamstring',
    mohannad: ['ANKSmhT0dTk', 'FMCq0hT3KRU', '0fuxdoKUCHA'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=lying+leg+curl+jeff+nippard',
    alternatives: ['standing_leg_curl', 'seated_leg_curl', 'rdl'],
    cue: 'Hips pressed into pad. Point toes — better hamstring activation.',
  },
  {
    id: 'standing_leg_curl',
    name: 'Standing Leg Curl',
    name_ar: 'ثني الرجل واقف',
    primary: ['hamstrings'],
    secondary: [],
    pattern: 'isolation_hamstring',
    mohannad: ['P2KTb8zyqsM'],
    jeff_nippard: 'https://www.youtube.com/results?search_query=standing+leg+curl+jeff+nippard',
    alternatives: ['prone_leg_curl', 'seated_leg_curl'],
    cue: 'One leg at a time. Brutal — you\'ll feel the stretch.',
  },
  {
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    name_ar: 'ثني الرجل جالس',
    primary: ['hamstrings'],
    secondary: [],
    pattern: 'isolation_hamstring',
    mohannad: [],
    jeff_nippard: 'https://www.youtube.com/shorts/Lh3iMIcbkBQ',
    alternatives: ['prone_leg_curl', 'standing_leg_curl'],
    cue: 'Hip-flexed position — better stretch on hamstrings than prone. Slow eccentric.',
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust (Machine or BB)',
    name_ar: 'دفع الورك',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    pattern: 'compound_hinge',
    mohannad: ['Va6Wg_jKilM', 'KPng97k1Opg'],
    jeff_nippard: 'https://www.youtube.com/watch?v=xDmFkJxPzeM',
    alternatives: ['rdl'],
    cue: 'Chin tucked. Squeeze glutes at top. Don\'t over-extend lower back.',
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlift (Week 3+)',
    name_ar: 'الرفعة الرومانية',
    primary: ['hamstrings'],
    secondary: ['glutes', 'back'],
    pattern: 'compound_hinge',
    mohannad: [],
    jeff_nippard: 'https://www.youtube.com/watch?v=_oyxCn2iSjU',
    alternatives: ['hip_thrust', 'prone_leg_curl'],
    cue: 'Hinge, don\'t squat. Bar slides down thighs. Stop when hamstrings stretch.',
  },
  {
    id: 'standing_calf',
    name: 'Standing Calf Raise',
    name_ar: 'سمانة واقف',
    primary: ['calves'],
    secondary: [],
    pattern: 'isolation_calf',
    mohannad: ['ArhbcO-TPKM', 'pHm6LFuGGbs', 'GnrwIpDtuto'],
    jeff_nippard: 'https://www.youtube.com/shorts/baEXLy09Ncc',
    alternatives: ['seated_calf'],
    cue: 'Full stretch at the bottom (1 sec pause), full contraction at top.',
  },
  {
    id: 'seated_calf',
    name: 'Seated Calf Raise',
    name_ar: 'سمانة جالس',
    primary: ['calves'],
    secondary: [],
    pattern: 'isolation_calf',
    mohannad: ['vCOlZ-zk80o'],
    jeff_nippard: 'https://www.youtube.com/shorts/baEXLy09Ncc',
    alternatives: ['standing_calf'],
    cue: 'Targets soleus. Slow, controlled — calves love volume.',
  },
  {
    id: 'ab_crunch',
    name: 'Ab Crunch (Machine or Cable)',
    name_ar: 'بطن',
    primary: ['abs'],
    secondary: [],
    pattern: 'isolation_core',
    mohannad: ['vBhXL83WbII'],
    jeff_nippard: 'https://www.youtube.com/watch?v=1G0y8D5rFDc',
    alternatives: [],
    cue: 'Curl spine, don\'t hinge at hips. Exhale at peak contraction.',
  },
];

// ---- Programme: 12 weeks, 3 blocks of 4 weeks --------------
// Block 1 (Weeks 1-4) = trimmed full-body for calibration.
// Block 2 (Weeks 5-8) = adds volume + RDL + pec deck.
// Block 3 (Weeks 9-12) = peak. Week 12 = deload.
//
// Format per session: { day, name, exercises: [{exercise_id, sets, reps, start_kg, rpe, is_first_of_muscle}] }
// `is_first_of_muscle` triggers the warmup prompt.
const PROGRAMME = {
  block: 1,
  block_name: 'Block 1 — Calibration (Weeks 1–4)',
  weeks: 4,
  notes: [
    'First exercise of each muscle gets 2 warm-up sets (50% × 10, 75% × 6). Other exercises: 1 light set or none.',
    'RPE target 7–8 on all working sets (3 reps in the tank).',
    'Add weight when you hit top of rep range at RPE 7–8 for 2 consecutive sessions: upper +2.5 kg, lower +5 kg, accessories +reps before +kg.',
    'Week 1 is calibration. If anything feels too light, flag it for next session. Don\'t grind.',
    'No barbell back squat or conventional deadlift yet. Romanian Deadlift introduced in Block 2.',
  ],
  sessions: [
    {
      id: 'session_a',
      day: 'Tuesday',
      name: 'Session A — Quad-dominant + horizontal push + vertical pull',
      mood: 'Focused. Heavy compounds early. Build, don\'t grind.',
      playlists: {
        spotify: [
          { label: 'Beast Mode',        url: 'https://open.spotify.com/playlist/37i9dQZF1DX76Wlfdnj7AP', vibe: 'Hip-hop heavy, classics' },
          { label: 'Power Workout',     url: 'https://open.spotify.com/playlist/37i9dQZF1DX35oM5SPECmN', vibe: 'High BPM, pump' },
          { label: 'Workout Twerkout',  url: 'https://open.spotify.com/playlist/37i9dQZF1DWUVpAXiEPK8P', vibe: 'Rap, deep groove' },
        ],
        youtube_music: [
          { label: 'Workout — Heavy Lifting', url: 'https://music.youtube.com/search?q=heavy+lifting+workout+playlist', vibe: 'Search; pick algorithm' },
          { label: 'Hip-Hop Gym',             url: 'https://music.youtube.com/search?q=hip+hop+gym+playlist', vibe: 'Rap, focus' },
          { label: 'Hard Rap Workout',        url: 'https://music.youtube.com/search?q=hard+rap+workout', vibe: 'Aggressive' },
        ],
        apple_music: [
          { label: 'Pure Workout',   url: 'https://music.apple.com/us/playlist/pure-workout/pl.b5e8e7b97d404cffb7b0be9b9c9d84f7', vibe: 'Curated bangers' },
          { label: 'Hip-Hop Workout', url: 'https://music.apple.com/us/playlist/hip-hop-workout/pl.45eb2cdec7c647519ad1e25c9d041b9f', vibe: 'Rap-driven' },
          { label: 'Pump Up',         url: 'https://music.apple.com/us/playlist/pump-up/pl.d77b5b47abc545f9b6dd7ca99e7ecf9b', vibe: 'High energy' },
        ],
      },
      exercises: [
        { exercise_id: 'leg_press',            sets: 3, reps: '10',    start_kg: 60,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 30kg×10, 45kg×6' },
        { exercise_id: 'incline_chest_press',  sets: 3, reps: '10',    start_kg: 25,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 12.5kg×10, 20kg×6' },
        { exercise_id: 'lat_pulldown',         sets: 3, reps: '10',    start_kg: 30,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 15kg×10, 22.5kg×6' },
        { exercise_id: 'leg_extension',        sets: 3, reps: '12',    start_kg: 17.5, rpe: '7-8', is_first_of_muscle: false },
        { exercise_id: 'lateral_raise_db',     sets: 3, reps: '12-15', start_kg: 4,    rpe: '8',   is_first_of_muscle: true,  warmup: '1 light set' },
      ],
    },
    {
      id: 'session_b',
      day: 'Saturday',
      name: 'Session B — Hip-dominant + horizontal push + vertical pull variant',
      mood: 'Weekend energy. Glutes lead. Slower tempo, more time under tension.',
      playlists: {
        spotify: [
          { label: 'Mood Booster',  url: 'https://open.spotify.com/playlist/37i9dQZF1DX3rxVfibe1L0', vibe: 'Upbeat, less aggressive' },
          { label: 'Rock Hard',     url: 'https://open.spotify.com/playlist/37i9dQZF1DWWJOmJ7nRx0C', vibe: 'Rock for hip thrusts' },
          { label: 'Locker Room',   url: 'https://open.spotify.com/playlist/37i9dQZF1DX6n3yo7jHCsj', vibe: 'Tempo, steady' },
        ],
        youtube_music: [
          { label: 'Mood Booster',     url: 'https://music.youtube.com/search?q=mood+booster+workout', vibe: 'Upbeat search' },
          { label: 'Workout Rock',     url: 'https://music.youtube.com/search?q=workout+rock+playlist', vibe: 'Rock energy' },
          { label: 'Pop Workout',      url: 'https://music.youtube.com/search?q=pop+workout+playlist', vibe: 'Upbeat pop' },
        ],
        apple_music: [
          { label: 'Pop Workout',     url: 'https://music.apple.com/us/playlist/pop-workout/pl.bdbb1395ec1843ada06afde26ed30734', vibe: 'Pop bangers' },
          { label: 'Rock Workout',    url: 'https://music.apple.com/us/playlist/rock-workout/pl.6125c1ca00794c4a930d72aaadbc55f0', vibe: 'Rock-driven' },
          { label: 'Cardio',          url: 'https://music.apple.com/us/playlist/cardio/pl.0adfb46c0b984e3e8a3d2ac5e3066d6e', vibe: 'Steady BPM' },
        ],
      },
      exercises: [
        { exercise_id: 'hip_thrust',           sets: 3, reps: '10',    start_kg: 20,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 10kg×10, 15kg×6' },
        { exercise_id: 'chest_press_machine',  sets: 3, reps: '10',    start_kg: 25,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 12.5kg×10, 20kg×6' },
        { exercise_id: 'lat_pulldown_neutral', sets: 3, reps: '10',    start_kg: 30,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 15kg×10, 22.5kg×6' },
        { exercise_id: 'prone_leg_curl',       sets: 3, reps: '12',    start_kg: 10,   rpe: '7-8', is_first_of_muscle: true,  warmup: '1 light set' },
        { exercise_id: 'face_pull',            sets: 3, reps: '15',    start_kg: 10,   rpe: '8',   is_first_of_muscle: true,  warmup: '0 sets — go straight in' },
      ],
    },
  ],
};

// ---- PPL programme (3 days/week alternative) ----------------
// Activates when settings.programme_variant === 'ppl_3x'.
// Same Block 1 calibration philosophy, just split across 3 sessions.
const PROGRAMME_PPL = {
  block: 1,
  block_name: 'Block 1 — Calibration (Weeks 1–4) — PPL 3×',
  weeks: 4,
  notes: [
    'Same calibration rules as full-body. RPE 7–8. No grind.',
    'Pick any 3 days that give 24h+ rest between adjacent sessions (Sat/Mon/Wed works well).',
    'Order is fixed: Push → Pull → Legs. Loop. The app shows what\'s next based on history, not day-of-week.',
    'Romanian Deadlift introduced Block 2. No barbell back squat in Block 1.',
  ],
  sessions: [
    {
      id: 'ppl_push',
      day: 'Push',
      name: 'Push — Chest, shoulders, triceps',
      mood: 'Big presses first. Save shoulders + tris for the back half.',
      playlists: {
        spotify: [
          { label: 'Beast Mode',        url: 'https://open.spotify.com/playlist/37i9dQZF1DX76Wlfdnj7AP', vibe: 'Hip-hop heavy' },
          { label: 'Power Workout',     url: 'https://open.spotify.com/playlist/37i9dQZF1DX35oM5SPECmN', vibe: 'High BPM' },
        ],
        youtube_music: [
          { label: 'Heavy Lifting',     url: 'https://music.youtube.com/search?q=heavy+lifting+workout+playlist', vibe: 'Search' },
          { label: 'Hip-Hop Gym',       url: 'https://music.youtube.com/search?q=hip+hop+gym+playlist', vibe: 'Rap focus' },
        ],
        apple_music: [
          { label: 'Pure Workout',      url: 'https://music.apple.com/us/playlist/pure-workout/pl.b5e8e7b97d404cffb7b0be9b9c9d84f7', vibe: 'Curated' },
          { label: 'Pump Up',           url: 'https://music.apple.com/us/playlist/pump-up/pl.d77b5b47abc545f9b6dd7ca99e7ecf9b', vibe: 'High energy' },
        ],
      },
      exercises: [
        { exercise_id: 'incline_chest_press',  sets: 3, reps: '10',     start_kg: 25,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 12.5kg×10, 20kg×6' },
        { exercise_id: 'chest_press_machine',  sets: 3, reps: '10',     start_kg: 25,   rpe: '7-8', is_first_of_muscle: false, warmup: '0 sets — chest is warm' },
        { exercise_id: 'shoulder_press_machine', sets: 3, reps: '10',   start_kg: 7.5,  rpe: '7-8', is_first_of_muscle: true,  warmup: '1 light set' },
        { exercise_id: 'lateral_raise_db',     sets: 3, reps: '12-15',  start_kg: 4,    rpe: '8',   is_first_of_muscle: false },
        { exercise_id: 'tricep_pushdown',      sets: 3, reps: '12',     start_kg: 15,   rpe: '8',   is_first_of_muscle: true,  warmup: '0 sets' },
      ],
    },
    {
      id: 'ppl_pull',
      day: 'Pull',
      name: 'Pull — Back, rear delts, biceps',
      mood: 'Squeeze every rep. Slow eccentric. Pull with your back, not your arms.',
      playlists: {
        spotify: [
          { label: 'Workout Twerkout', url: 'https://open.spotify.com/playlist/37i9dQZF1DWUVpAXiEPK8P', vibe: 'Rap, deep groove' },
          { label: 'Power Workout',    url: 'https://open.spotify.com/playlist/37i9dQZF1DX35oM5SPECmN', vibe: 'High BPM' },
        ],
        youtube_music: [
          { label: 'Pull Day',         url: 'https://music.youtube.com/search?q=pull+day+workout', vibe: 'Search' },
          { label: 'Hip-Hop Gym',      url: 'https://music.youtube.com/search?q=hip+hop+gym+playlist', vibe: 'Rap' },
        ],
        apple_music: [
          { label: 'Hip-Hop Workout',  url: 'https://music.apple.com/us/playlist/hip-hop-workout/pl.45eb2cdec7c647519ad1e25c9d041b9f', vibe: 'Rap-driven' },
        ],
      },
      exercises: [
        { exercise_id: 'lat_pulldown',         sets: 3, reps: '10',     start_kg: 30,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 15kg×10, 22.5kg×6' },
        { exercise_id: 'seated_cable_row',     sets: 3, reps: '10',     start_kg: 25,   rpe: '7-8', is_first_of_muscle: false, warmup: '1 light set' },
        { exercise_id: 'face_pull',            sets: 3, reps: '15',     start_kg: 10,   rpe: '8',   is_first_of_muscle: true,  warmup: '0 sets' },
        { exercise_id: 'biceps_curl',          sets: 3, reps: '12',     start_kg: 5,    rpe: '8',   is_first_of_muscle: true,  warmup: '0 sets' },
        { exercise_id: 'hammer_curl',          sets: 3, reps: '12',     start_kg: 4,    rpe: '8',   is_first_of_muscle: false },
      ],
    },
    {
      id: 'ppl_legs',
      day: 'Legs',
      name: 'Legs — Quads, glutes, hamstrings, calves',
      mood: 'Long session. Pace yourself. The pump on this day is real.',
      playlists: {
        spotify: [
          { label: 'Beast Mode',       url: 'https://open.spotify.com/playlist/37i9dQZF1DX76Wlfdnj7AP', vibe: 'Hip-hop heavy' },
          { label: 'Locker Room',      url: 'https://open.spotify.com/playlist/37i9dQZF1DX6n3yo7jHCsj', vibe: 'Tempo' },
        ],
        youtube_music: [
          { label: 'Leg Day',          url: 'https://music.youtube.com/search?q=leg+day+workout', vibe: 'Search' },
          { label: 'Heavy Lifting',    url: 'https://music.youtube.com/search?q=heavy+lifting+workout+playlist', vibe: 'Search' },
        ],
        apple_music: [
          { label: 'Pure Workout',     url: 'https://music.apple.com/us/playlist/pure-workout/pl.b5e8e7b97d404cffb7b0be9b9c9d84f7', vibe: 'Curated' },
        ],
      },
      exercises: [
        { exercise_id: 'leg_press',            sets: 3, reps: '10',     start_kg: 60,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 30kg×10, 45kg×6' },
        { exercise_id: 'leg_extension',        sets: 3, reps: '12',     start_kg: 17.5, rpe: '7-8', is_first_of_muscle: false, warmup: '0 sets — quads warm' },
        { exercise_id: 'hip_thrust',           sets: 3, reps: '10',     start_kg: 20,   rpe: '7',   is_first_of_muscle: true,  warmup: '2 sets: 10kg×10, 15kg×6' },
        { exercise_id: 'prone_leg_curl',       sets: 3, reps: '12',     start_kg: 10,   rpe: '7-8', is_first_of_muscle: true,  warmup: '1 light set' },
        { exercise_id: 'standing_calf',        sets: 3, reps: '15',     start_kg: 25,   rpe: '8',   is_first_of_muscle: true,  warmup: '0 sets' },
      ],
    },
  ],
};

// ---- Athlete profile (from SKILL.md) ------------------------
const ATHLETE = {
  name: 'Raed',
  goal: 'Body recomposition — muscle gain + fat loss',
  experience: 'Returning beginner (2-year layoff)',
  schedule: 'Tuesday + Saturday AM',
  session_cap_min: 80,
  bodyweight_kg: 82,
  protein_target_g: '130–160',
  injuries: 'None confirmed',
  supplements: ['Creatine', 'Lion\'s Mane', 'Vitamin D', 'Fish liver oil'],
  chest_priority: true,
  rules: [
    'Never grind to failure on Block 1.',
    'Technique > weight. Always.',
    'No barbell back squat or conventional deadlift until form review.',
    'Eat 130–160g protein/day or training does nothing.',
    'Sleep ≥7h or skip the gym — under-recovered training is just damage.',
  ],
};

const FAMILY_PROFILES = [
  { user_id: 'Raed', display_name: 'Raed', experience: 'returning', bodyweight_kg: 82, allowlisted: true },
  { user_id: 'bassam', display_name: 'Bassam', experience: 'returning', bodyweight_kg: null, allowlisted: true },
  { user_id: 'abdullah', display_name: 'Abdullah', experience: 'beginner', bodyweight_kg: null, allowlisted: true },
];

// ---- Motivational end-of-session messages -------------------
// Rotate one per session. Mix of recovery/nutrition/process reminders.
const MOTIVATIONAL_MESSAGES = [
  'بروتين اليوم: 130–160 جم. لا تنام قبل ما تحسب.',
  'نوم ≥ 7 ساعات الليلة. النوم هو اللي يبني، مش الجلسة.',
  'اشرب 2 لتر ماء قبل الغروب. الجفاف يقلل القوة 10%.',
  'مشي 8000 خطوة يوم الراحة. NEAT أهم من الكارديو.',
  'لا تزن نفسك يومياً. يوم في الأسبوع، صباحاً، ريق.',
  'لو كنت متعب اليوم، يومين راحة أحسن من جلسة سيئة.',
  'الـ creatine اليومية: 5 جم. ما تفرق متى تأخذها.',
  'القياس الحقيقي: الصور كل أسبوعين، نفس الإضاءة.',
  'لو طلعت متوتر من الشغل، الجلسة تذيب التوتر. اطلع.',
  'الكافيين قبل الجيم بـ 30 دقيقة. مش بعد، مش معاه.',
  'عضلاتك تكبر وأنت نايم، مش وأنت ترفع.',
  'أسبوع ضعيف لا يعني شي. شهر ضعيف، نراجع.',
  'لا تقارن جلستك اليوم بجلسة محسن. قارنها بجلستك الماضية.',
  'الـ stretching بعد الجلسة 5 دقائق. كافي.',
  'وجبة بعد الجيم خلال ساعة. بروتين + كارب.',
  'لو ركبتك تؤلم، أوقف. الألم ≠ التحدي.',
  'الانتظام أهم من الشدة. كل أسبوع، حتى لو ضعيف.',
  'ما في تمرين سحري. كلهم يعطون نتائج لو نفّذتهم صح.',
  'اللي يفرق بعد سنة: من جا، مش من رفع أكثر.',
  'هذي جلستك. لا تشاركها على instagram. ركّز.',
];

// Export to global scope for the app
window.RW = { MUSCLES, EXERCISES, PROGRAMME, PROGRAMME_PPL, ATHLETE, FAMILY_PROFILES, MOTIVATIONAL_MESSAGES, yt, ytShort, thumb, bodyImg, BODY_IMG };
